# Generated by Django 5.0.6 on 2024-06-05 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0002_alter_permission_name_alter_role_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permission',
            table='permissions',
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acl.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acl.role')),
            ],
            options={
                'db_table': 'role_permissions',
            },
        ),
    ]
