# Generated by Django 5.0.6 on 2024-06-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0004_role_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='acl.RolePermission', to='acl.permission'),
        ),
    ]
