# Generated by Django 5.0.6 on 2024-06-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
