# Generated by Django 5.0.6 on 2024-06-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'timezones',
            },
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
