# Generated by Django 5.0.6 on 2024-06-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_template_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_custom_template',
            field=models.BooleanField(default=True),
        ),
    ]
